<?php
$content = file_get_contents("php://input");
$token = '1892943113:AAEXurCn1CndT7n56RUA4Jr1Ru-opuIt4Wg';
$apiLink = "https://api.telegram.org/bot$token/"; 
$update = json_decode($content, true);
if(!@$update["message"]) $val = $update['callback_query'];
else $val = $update;
$chat_id = $val['message']['chat']['id'];
$text = $val['message']['text'];
$update_id = $val['update_id'];
$sender = $val['message']['from'];

if ($text == "/start") {
    file_get_contents($apiLink . "sendmessage?chat_id=$chat_id&text=Kamu bisa membuat sudoku dengan format PDF.");
    return false;
} else if ($text == "/donasi") {
    file_get_contents($apiLink . "sendmessage?chat_id=$chat_id&text=Untuk donasi developer, silahkan kunjungi: https://saweria.co/rasitech");
    return false;
} else if ($text == "/about") {
    file_get_contents($apiLink . "sendmessage?chat_id=$chat_id&text=Bot ini dibuat oleh @RasiTechChannel. Bot ini diintegrasikan dengan API SimSimi langsung.");
    return false;
} else if ($text == "/versi") {
    file_get_contents($apiLink . "sendmessage?chat_id=$chat_id&text=Bot ini versi 1.0.0");
    return false;
} else if ($text == "/generate") {
    $a = "http://www.opensky.ca/~jdhildeb/software/sudokugen/generate?number=20&perPage=1&difficulty=Easy&_action_generate=Go";
    file_get_contents($apiLink . "sendDocument?chat_id=$chat_id&document=$a&caption=Generated By @RTSudoku_bot");
    return false;
}
